# Workflow para compilar um projeto Node.js e fazer deploy no GitHub Pages
name: Deploy Node.js to GitHub Pages

on:
  # Roda em pushes direcionados à branch padrão
  push:
    branches: ["main"]

  # Permite que você rode este workflow manualmente pela aba Actions
  workflow_dispatch:

# Define permissões do GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # --- Etapas Modificadas para Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Especifique a versão do Node que seu projeto usa
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci # 'ci' é geralmente preferido em vez de 'install' em workflows
        
      - name: Build project
        run: npm run build # Este é o comando que gera os arquivos estáticos
      # --- Fim das Etapas Modificadas ---
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O 'npm run build' geralmente cria uma pasta 'dist' ou 'build'
          # Verifique a configuração do seu projeto e ajuste o path se necessário
          path: './dist' 

  # Job de Deploy (permanece o mesmo)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
